from django.contrib import admin
from django.urls import path

from core import views


urlpatterns = [
    path("", views.index, name="index"),
    path("app.js", views.asset, {"filename": "app.js"}, name="app_js"),
    path("styles.css", views.asset, {"filename": "styles.css"}, name="styles_css"),
    path("rozledger-logo.png", views.asset, {"filename": "rozledger-logo.png"}, name="logo_png"),
    path("robots.txt", views.asset, {"filename": "robots.txt"}, name="robots_txt"),
    path("sitemap.xml", views.asset, {"filename": "sitemap.xml"}, name="sitemap_xml"),
    path("content/", views.content_index, name="content_index"),
    path("blog/", views.blog_index, name="blog_index"),
    path("privacy/", views.privacy, name="privacy"),
    path("terms/", views.terms, name="terms"),
    path("contact/", views.contact, name="contact"),
    path("pricing/", views.pricing, name="pricing"),
    path("pages/<slug:slug>/", views.seo_page, name="seo_page"),
    path("blog/<slug:slug>/", views.blog_page, name="blog_page"),
    path("invoice/<str:token>/", views.invoice_print, name="invoice_print"),
    path("invoice/<str:token>/download.pdf", views.invoice_pdf, name="invoice_pdf"),
    path("pro/thanks/<str:token>/", views.lead_thanks, name="lead_thanks"),
    path("pro/request/", views.create_lead_form, name="lead_request_form"),
    path("accounts/register/", views.register_view, name="register"),
    path("accounts/login/", views.login_view, name="login"),
    path("accounts/logout/", views.logout_view, name="logout"),
    path("accounts/password-reset/", views.password_reset_view, name="password_reset"),
    path("accounts/reset/<str:uidb64>/<str:token>/", views.password_reset_confirm_view, name="password_reset_confirm"),
    path("dashboard/", views.dashboard, name="dashboard"),
    path("dashboard/clients/", views.create_client, name="create_client"),
    path("dashboard/invoices/new/", views.invoice_new, name="invoice_new"),
    path("dashboard/invoices/<int:invoice_id>/edit/", views.invoice_edit, name="invoice_edit"),
    path("dashboard/invoices/<int:invoice_id>/status/", views.invoice_status, name="invoice_status"),
    path("dashboard/invoices/<int:invoice_id>/delete/", views.invoice_delete, name="invoice_delete"),
    path("dashboard/billing/pro/", views.pro_billing, name="pro_billing"),
    path("dashboard/billing/request-pro/", views.request_pro_activation, name="request_pro_activation"),
    path("admin/", admin.site.urls),
    path("api/health", views.health, name="health"),
    path("api/options", views.options, name="options"),
    path("api/leads", views.create_lead, name="create_lead"),
    path("api/invoices", views.create_invoice, name="create_invoice"),
    path("api/affiliate-clicks", views.affiliate_click, name="affiliate_click"),
]
