# Generated by Django 5.0.6 on 2026-05-31 18:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_profiles_and_clients(apps, schema_editor):
    Invoice = apps.get_model("core", "Invoice")
    Client = apps.get_model("core", "Client")
    BusinessProfile = apps.get_model("core", "BusinessProfile")

    for invoice in Invoice.objects.exclude(owner_email="").order_by("created_at", "id"):
        BusinessProfile.objects.update_or_create(
            owner_email=invoice.owner_email,
            defaults={
                "owner_id": invoice.owner_id,
                "business_name": invoice.business_name,
                "business_logo": invoice.business_logo,
                "business_address": invoice.business_address,
                "upi_link": invoice.upi_link,
                "bank_details": invoice.bank_details,
                "thank_you_note": invoice.thank_you_note,
                "template": invoice.template,
                "accent_color": invoice.accent_color,
            },
        )
        if invoice.client_name:
            Client.objects.update_or_create(
                owner_email=invoice.owner_email,
                name=invoice.client_name,
                defaults={
                    "owner_id": invoice.owner_id,
                    "address": invoice.client_address,
                    "gstin": invoice.client_gstin,
                },
            )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_invoice_template_accent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_email', models.EmailField(max_length=254, unique=True)),
                ('business_name', models.CharField(max_length=180)),
                ('business_logo', models.FileField(blank=True, upload_to='business_logos/%Y/%m/')),
                ('business_address', models.TextField(blank=True)),
                ('gstin', models.CharField(blank=True, max_length=20)),
                ('upi_link', models.TextField(blank=True)),
                ('bank_details', models.TextField(blank=True)),
                ('thank_you_note', models.TextField(blank=True)),
                ('template', models.CharField(choices=[('classic', 'Classic Ledger'), ('executive', 'Executive Black'), ('modern', 'Modern Accent'), ('minimal', 'Minimal Clean'), ('service', 'Service Pro')], default='classic', max_length=20)),
                ('accent_color', models.CharField(default='#126b4f', max_length=7)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='business_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['business_name'],
            },
        ),
        migrations.RunPython(backfill_profiles_and_clients, migrations.RunPython.noop),
    ]
