# Generated by Django 5.0.6 on 2026-06-04 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_client_address_businessprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='currency_symbol',
            field=models.CharField(default='\u20b9', max_length=8),
        ),
        migrations.AddField(
            model_name='invoice',
            name='tax_label',
            field=models.CharField(default='GST', max_length=40),
        ),
    ]
