# Generated by Django 5.0.6 on 2026-06-04 18:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_invoice_business_client_phone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='paymentgatewayconfig',
            options={'ordering': ['market', 'gateway']},
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='businessprofile',
            name='market',
            field=models.CharField(choices=[('IN', 'India'), ('US', 'United States')], db_index=True, default='IN', max_length=2),
        ),
        migrations.AddField(
            model_name='client',
            name='market',
            field=models.CharField(choices=[('IN', 'India'), ('US', 'United States')], db_index=True, default='IN', max_length=2),
        ),
        migrations.AddField(
            model_name='invoice',
            name='market',
            field=models.CharField(choices=[('IN', 'India'), ('US', 'United States')], db_index=True, default='IN', max_length=2),
        ),
        migrations.AddField(
            model_name='lead',
            name='market',
            field=models.CharField(choices=[('IN', 'India'), ('US', 'United States')], db_index=True, default='IN', max_length=2),
        ),
        migrations.AddField(
            model_name='paymentgatewayconfig',
            name='market',
            field=models.CharField(choices=[('IN', 'India'), ('US', 'United States')], db_index=True, default='IN', max_length=2),
        ),
        migrations.AddField(
            model_name='plansubscription',
            name='market',
            field=models.CharField(choices=[('IN', 'India'), ('US', 'United States')], db_index=True, default='IN', max_length=2),
        ),
        migrations.AlterField(
            model_name='businessprofile',
            name='owner_email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='paymentgatewayconfig',
            name='gateway',
            field=models.CharField(choices=[('razorpay', 'Razorpay'), ('stripe', 'Stripe'), ('paypal', 'PayPal')], default='razorpay', max_length=30),
        ),
        migrations.AlterField(
            model_name='plansubscription',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='plansubscription',
            name='owner_email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterUniqueTogether(
            name='businessprofile',
            unique_together={('market', 'owner_email')},
        ),
        migrations.AlterUniqueTogether(
            name='client',
            unique_together={('market', 'owner_email', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='paymentgatewayconfig',
            unique_together={('market', 'gateway')},
        ),
        migrations.AlterUniqueTogether(
            name='plansubscription',
            unique_together={('market', 'owner_email')},
        ),
    ]
