# Generated by Django 5.0.6 on 2026-06-04 20:02

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_account_journalentry_journalline'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(choices=[('IN', 'India'), ('US', 'United States')], db_index=True, default='IN', max_length=2)),
                ('owner_email', models.EmailField(db_index=True, max_length=254)),
                ('payment_date', models.DateField(default=django.utils.timezone.localdate)),
                ('payer_name', models.CharField(max_length=180)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('bank', 'Bank transfer'), ('cash', 'Cash'), ('upi', 'UPI'), ('card', 'Card'), ('check', 'Check'), ('paypal', 'PayPal'), ('stripe', 'Stripe'), ('other', 'Other')], default='bank', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='core.invoice')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_receipts', to='core.journalentry')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_receipts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VendorBill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(choices=[('IN', 'India'), ('US', 'United States')], db_index=True, default='IN', max_length=2)),
                ('owner_email', models.EmailField(db_index=True, max_length=254)),
                ('bill_date', models.DateField(default=django.utils.timezone.localdate)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('vendor_name', models.CharField(max_length=180)),
                ('category', models.CharField(default='Office expenses', max_length=180)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], db_index=True, default='unpaid', max_length=20)),
                ('payment_method', models.CharField(choices=[('bank', 'Bank transfer'), ('cash', 'Cash'), ('upi', 'UPI'), ('card', 'Card'), ('check', 'Check'), ('paypal', 'PayPal'), ('stripe', 'Stripe'), ('other', 'Other')], default='bank', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_bills', to='core.journalentry')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_bills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-bill_date', '-created_at'],
            },
        ),
    ]
