# Generated by Django 5.0.6 on 2026-06-05 17:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_invoicelineitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='business_type',
            field=models.CharField(choices=[('service', 'Service business'), ('trading', 'Trading / retail'), ('manufacturing', 'Manufacturing'), ('travel', 'Travel & tour operator'), ('professional', 'Professional firm'), ('construction', 'Construction / contractor'), ('restaurant', 'Restaurant / food service'), ('education', 'Education / coaching'), ('healthcare', 'Healthcare / clinic'), ('other', 'Other business')], default='service', max_length=30),
        ),
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(choices=[('IN', 'India'), ('US', 'United States')], db_index=True, default='IN', max_length=2)),
                ('owner_email', models.EmailField(db_index=True, max_length=254)),
                ('sku', models.CharField(blank=True, max_length=80)),
                ('name', models.CharField(max_length=180)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('item_type', models.CharField(choices=[('service', 'Service'), ('trading', 'Trading item'), ('raw_material', 'Raw material'), ('finished_goods', 'Finished goods'), ('package', 'Travel/package item'), ('consumable', 'Consumable')], default='trading', max_length=30)),
                ('unit', models.CharField(default='pcs', max_length=30)),
                ('sales_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('purchase_rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reorder_level', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('track_inventory', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(choices=[('IN', 'India'), ('US', 'United States')], db_index=True, default='IN', max_length=2)),
                ('owner_email', models.EmailField(db_index=True, max_length=254)),
                ('movement_type', models.CharField(choices=[('opening', 'Opening balance'), ('purchase', 'Purchase / inward'), ('sale', 'Sale / outward'), ('adjustment', 'Adjustment'), ('production', 'Production'), ('return', 'Return')], max_length=30)),
                ('movement_date', models.DateField(default=django.utils.timezone.localdate)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='core.inventoryitem')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-movement_date', '-created_at'],
            },
        ),
    ]
