# Generated by Django 5.0.6 on 2026-06-05 19:03

import core.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_godown_stockmovement_godown_stockcostlayer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseUploadDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_token', models.CharField(default=core.models.public_token, editable=False, max_length=48, unique=True)),
                ('market', models.CharField(choices=[('IN', 'India'), ('US', 'United States')], db_index=True, default='IN', max_length=2)),
                ('owner_email', models.EmailField(db_index=True, max_length=254)),
                ('document', models.FileField(upload_to='expense_uploads/%Y/%m/')),
                ('original_filename', models.CharField(blank=True, max_length=240)),
                ('extracted_text', models.TextField(blank=True)),
                ('vendor_name', models.CharField(blank=True, max_length=180)),
                ('category', models.CharField(blank=True, max_length=180)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bill_date', models.DateField(default=django.utils.timezone.localdate)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('bill_status', models.CharField(choices=[('unpaid', 'Unpaid'), ('paid', 'Paid')], default='paid', max_length=20)),
                ('payment_method', models.CharField(choices=[('bank', 'Bank transfer'), ('cash', 'Cash'), ('upi', 'UPI'), ('card', 'Card'), ('check', 'Check'), ('paypal', 'PayPal'), ('stripe', 'Stripe'), ('other', 'Other')], default='bank', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='expense_upload_drafts', to=settings.AUTH_USER_MODEL)),
                ('vendor_bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload_drafts', to='core.vendorbill')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
