# Generated by Django 5.0.6 on 2026-06-05 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_expenseuploaddraft'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('sales', 'Sales'), ('purchase', 'Purchase'), ('expense', 'Expense'), ('receipt', 'Receipt'), ('payment', 'Payment'), ('contra', 'Contra'), ('journal', 'Journal'), ('stock_journal', 'Stock journal')], max_length=30),
        ),
    ]
