# Generated by Django 5.0.6 on 2026-06-06 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_voucher_voucher_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentreceipt',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_receipts', to='core.voucher'),
        ),
        migrations.AddField(
            model_name='vendorbill',
            name='paid_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vendorbill',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='vendorbill',
            name='payment_voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_vendor_bills', to='core.voucher'),
        ),
        migrations.AddField(
            model_name='vendorbill',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_bills', to='core.voucher'),
        ),
    ]
