# Generated by Django 5.0.6 on 2026-06-06 03:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_paymentreceipt_voucher_vendorbill_paid_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='sales_voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_invoices', to='core.voucher'),
        ),
    ]
