# Generated by Django 5.0.6 on 2026-06-06 04:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_invoice_sales_voucher'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenseuploaddraft',
            name='bill_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('partially_paid', 'Partially paid'), ('paid', 'Paid')], default='paid', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('partially_paid', 'Partially paid'), ('paid', 'Paid'), ('overdue', 'Overdue')], db_index=True, default='sent', max_length=20),
        ),
        migrations.AlterField(
            model_name='vendorbill',
            name='status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('partially_paid', 'Partially paid'), ('paid', 'Paid')], db_index=True, default='unpaid', max_length=20),
        ),
        migrations.CreateModel(
            name='VendorBillPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(choices=[('IN', 'India'), ('US', 'United States')], db_index=True, default='IN', max_length=2)),
                ('owner_email', models.EmailField(db_index=True, max_length=254)),
                ('payment_date', models.DateField(default=django.utils.timezone.localdate)),
                ('vendor_name', models.CharField(max_length=180)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('method', models.CharField(choices=[('bank', 'Bank transfer'), ('cash', 'Cash'), ('upi', 'UPI'), ('card', 'Card'), ('check', 'Check'), ('paypal', 'PayPal'), ('stripe', 'Stripe'), ('other', 'Other')], default='bank', max_length=20)),
                ('reference', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.vendorbill')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_bill_payments', to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_bill_payments', to='core.voucher')),
            ],
            options={
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
    ]
