# Generated by Django 5.0.6 on 2026-06-06 09:33

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_alter_expenseuploaddraft_bill_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('partially_paid', 'Partially paid'), ('partially_credited', 'Partially credited'), ('paid', 'Paid'), ('credited', 'Credited'), ('overdue', 'Overdue')], db_index=True, default='sent', max_length=20),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('sales', 'Sales'), ('purchase', 'Purchase'), ('expense', 'Expense'), ('receipt', 'Receipt'), ('credit_note', 'Credit note'), ('payment', 'Payment'), ('contra', 'Contra'), ('journal', 'Journal'), ('stock_journal', 'Stock journal')], max_length=30),
        ),
        migrations.CreateModel(
            name='CustomerCreditNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(choices=[('IN', 'India'), ('US', 'United States')], db_index=True, default='IN', max_length=2)),
                ('owner_email', models.EmailField(db_index=True, max_length=254)),
                ('credit_note_number', models.CharField(max_length=60)),
                ('credit_date', models.DateField(default=django.utils.timezone.localdate)),
                ('client_name', models.CharField(max_length=180)),
                ('taxable_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(max_length=240)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_notes', to='core.invoice')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_credit_notes', to='core.journalentry')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_credit_notes', to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_credit_notes', to='core.voucher')),
            ],
            options={
                'ordering': ['-credit_date', '-created_at'],
                'unique_together': {('market', 'owner_email', 'credit_note_number')},
            },
        ),
    ]
