# Generated by Django 5.0.6 on 2026-06-06 19:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_invoice_status_alter_voucher_voucher_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='voucher_type',
            field=models.CharField(choices=[('sales', 'Sales'), ('purchase', 'Purchase'), ('expense', 'Expense'), ('receipt', 'Receipt'), ('credit_note', 'Credit note'), ('debit_note', 'Debit note'), ('reversal', 'Reversal'), ('payment', 'Payment'), ('contra', 'Contra'), ('journal', 'Journal'), ('stock_journal', 'Stock journal')], max_length=30),
        ),
        migrations.CreateModel(
            name='ReconciliationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(choices=[('IN', 'India'), ('US', 'United States')], db_index=True, default='IN', max_length=2)),
                ('owner_email', models.EmailField(db_index=True, max_length=254)),
                ('statement_date', models.DateField(default=django.utils.timezone.localdate)),
                ('date_from', models.DateField(blank=True, null=True)),
                ('date_to', models.DateField(blank=True, null=True)),
                ('statement_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ledger_balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('difference', models.DecimalField(decimal_places=2, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reconciliation_sessions', to='core.account')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-statement_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentReversal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(choices=[('IN', 'India'), ('US', 'United States')], db_index=True, default='IN', max_length=2)),
                ('owner_email', models.EmailField(db_index=True, max_length=254)),
                ('reversal_type', models.CharField(choices=[('customer_receipt', 'Customer receipt'), ('vendor_payment', 'Vendor payment')], max_length=30)),
                ('reversal_number', models.CharField(max_length=60)),
                ('reversal_date', models.DateField(default=django.utils.timezone.localdate)),
                ('party_name', models.CharField(max_length=180)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(max_length=240)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer_receipt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reversals', to='core.paymentreceipt')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_reversals', to='core.journalentry')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_reversals', to=settings.AUTH_USER_MODEL)),
                ('vendor_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reversals', to='core.vendorbillpayment')),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_reversals', to='core.voucher')),
            ],
            options={
                'ordering': ['-reversal_date', '-created_at'],
                'unique_together': {('market', 'owner_email', 'reversal_number')},
            },
        ),
        migrations.CreateModel(
            name='ReconciliationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journal_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_lines', to='core.journalline')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='core.reconciliationsession')),
            ],
            options={
                'ordering': ['id'],
                'unique_together': {('session', 'journal_line')},
            },
        ),
        migrations.CreateModel(
            name='VendorDebitNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(choices=[('IN', 'India'), ('US', 'United States')], db_index=True, default='IN', max_length=2)),
                ('owner_email', models.EmailField(db_index=True, max_length=254)),
                ('debit_note_number', models.CharField(max_length=60)),
                ('debit_date', models.DateField(default=django.utils.timezone.localdate)),
                ('vendor_name', models.CharField(max_length=180)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.CharField(max_length=240)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debit_notes', to='core.vendorbill')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_debit_notes', to='core.journalentry')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_debit_notes', to=settings.AUTH_USER_MODEL)),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_debit_notes', to='core.voucher')),
            ],
            options={
                'ordering': ['-debit_date', '-created_at'],
                'unique_together': {('market', 'owner_email', 'debit_note_number')},
            },
        ),
    ]
