# Generated by Django 5.0.6 on 2026-06-08 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_voucher_voucher_type_reconciliationsession_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(default='razorpay', max_length=20)),
                ('event_id', models.CharField(max_length=120, unique=True)),
                ('event_type', models.CharField(db_index=True, max_length=80)),
                ('reference_id', models.CharField(blank=True, db_index=True, max_length=80)),
                ('summary', models.CharField(blank=True, max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='paymentgatewayconfig',
            name='razorpay_plan_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='paymentgatewayconfig',
            name='subscription_amount',
            field=models.PositiveIntegerField(default=29900, help_text='Recurring amount in the smallest currency unit (paise for INR, cents for USD).'),
        ),
        migrations.AddField(
            model_name='plansubscription',
            name='last_payment_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='plansubscription',
            name='provider',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='plansubscription',
            name='razorpay_customer_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='plansubscription',
            name='razorpay_subscription_id',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
