# Generated by Django 5.0.6 on 2026-06-08 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_paymentevent_paymentgatewayconfig_razorpay_plan_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='place_of_supply',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='invoice',
            name='reverse_charge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='invoice',
            name='seller_gstin',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='supply_type',
            field=models.CharField(choices=[('intra', 'Intra-state (CGST + SGST)'), ('inter', 'Inter-state (IGST)')], default='intra', max_length=10),
        ),
    ]
