# Generated by Django 5.0.6 on 2026-06-08 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_invoice_place_of_supply_invoice_reverse_charge_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GstnApiConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market', models.CharField(choices=[('IN', 'India'), ('US', 'United States')], db_index=True, default='IN', max_length=2)),
                ('provider', models.CharField(default='whitebooks', max_length=30)),
                ('enabled', models.BooleanField(default=False)),
                ('mode', models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], default='sandbox', max_length=12)),
                ('base_url', models.CharField(blank=True, help_text='GSP API base URL, e.g. https://api.whitebooks.in (no trailing slash).', max_length=200)),
                ('gstin', models.CharField(blank=True, help_text='Taxpayer GSTIN registered with the GSP.', max_length=20)),
                ('api_email', models.EmailField(blank=True, help_text="API login email (sent as the 'email' query parameter).", max_length=254)),
                ('ip_address', models.CharField(blank=True, help_text="Public IP registered with the GSP (the server's outbound IP).", max_length=50)),
                ('default_hsn', models.CharField(blank=True, help_text='Fallback HSN/SAC code used when an invoice line has none.', max_length=8)),
                ('encrypted_client_id', models.TextField(blank=True)),
                ('encrypted_client_secret', models.TextField(blank=True)),
                ('encrypted_username', models.TextField(blank=True)),
                ('encrypted_password', models.TextField(blank=True)),
                ('encrypted_auth_token', models.TextField(blank=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['market', 'provider'],
                'unique_together': {('market', 'provider')},
            },
        ),
    ]
