# Generated by Django 5.0.6 on 2026-06-08 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_gstnapiconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='document_type',
            field=models.CharField(choices=[('tax_invoice', 'Tax invoice'), ('proforma', 'Proforma invoice'), ('quotation', 'Quotation')], db_index=True, default='tax_invoice', max_length=20),
        ),
    ]
