# Generated by Django 5.0.6 on 2026-06-08 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_invoice_document_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessprofile',
            name='pos_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='gst_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
